### PR TITLE
Fix bug when use references type in function

### PR DESCRIPTION
**Pull request by tranleduy2000**
- add function_reference.pas in tests/compare
- some file change "tab character" because Intellij reformat code.

### CODE REVIEW

**Comment by jeremysalwen** [comment]
Hey, I think the issue with the variable by reference is a bug in another part of the code.  I am currently fixing it.

**Comment by tranleduy2000** [comment]
Can you help me code pointer type, I will be very happy for that.

**Comment by jeremysalwen** [comment]
I actually already had a lot of the framework in place for pointers.  I will work on it.  I am going to do a big reformatting of all the code and change tabs to spaces, so try to rebase after that change so you will not have a crazy merge

**Comment by jeremysalwen** [comment]
I have added support for basic pointer types in the latest commit.

**Pull request closed without merging**
