### PR TITLE
Update StringIndex.java

### PR DESCRIPTION
**Pull request by tranleduy2000**

### CODE REVIEW

**Comment by jeremysalwen** [comment]
I think it's a good idea for every bugfix to have a test added that will catch it.  None of our current tests catch this bug.  Do you think you could add a simple test that would demonstrate this bug?

**Comment by tranleduy2000** [comment]
https://github.com/tranleduy2000/JSPIIJ/commit/81a3f1731e2db4dfdc6732944fba1ef922783572
I can not create pull request

**Comment by jeremysalwen** [comment]
Why can't you create a pull request?

**Comment by jeremysalwen** [comment]
Tested and merged.

**Pull request merged**
